# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.17.5"
  # TODO: fix after upstream fix
  # https://github.com/package-url/packageurl-python/pull/201/files#r2257224277
  use_mypy: "1"

package:
  name: packageurl-python
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/packageurl-python/packageurl_python-${{ version }}.tar.gz
  sha256: a7be3f3ba70d705f738ace9bf6124f31920245a49fa69d4b416da7037dd2de61

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - packageurl
        - packageurl.contrib
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - if: use_mypy == "1"
    then:
      requirements:
        run:
          - mypy
          - python ${{ python_min }}.*
      script:
        - mypy -p packageurl --ignore-missing-imports

about:
  summary: A purl aka. Package URL parser and builder
  license: MIT
  license_file: mit.LICENSE
  homepage: https://github.com/package-url/packageurl-python

extra:
  recipe-maintainers:
    - bollwyvl
